// <auto-generated />
using System;
using GymManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260109225814_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymManagementSystem.Models.FitnessType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("FitnessTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Kardiyovasküler egzersizler, koşu bandı, bisiklet",
                            ImageUrl = "/images/fitness/cardio.jpg",
                            Name = "Kardio"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Kas geliştirme ve güç antrenmanları",
                            ImageUrl = "/images/fitness/weights.jpg",
                            Name = "Ağırlık Antrenmanı"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Esneklik, denge ve zihinsel rahatlama",
                            ImageUrl = "/images/fitness/yoga.jpg",
                            Name = "Yoga"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Core güçlendirme ve postür düzeltme",
                            ImageUrl = "/images/fitness/pilates.jpg",
                            Name = "Pilates"
                        });
                });

            modelBuilder.Entity("GymManagementSystem.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("TrainerId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ali@email.com",
                            FullName = "Ali Veli",
                            Phone = "0541 111 1111",
                            PlanId = 1,
                            RegistrationDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "zeynep@email.com",
                            FullName = "Zeynep Ak",
                            Phone = "0542 222 2222",
                            PlanId = 2,
                            RegistrationDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainerId = 2
                        });
                });

            modelBuilder.Entity("GymManagementSystem.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DurationMonths")
                        .HasColumnType("int");

                    b.Property<int>("FitnessTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FitnessTypeId");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Yeni başlayanlar için kardio programı",
                            DurationMonths = 1,
                            FitnessTypeId = 1,
                            Name = "Başlangıç Kardio",
                            Price = 500m
                        },
                        new
                        {
                            Id = 2,
                            Description = "İleri seviye ağırlık antrenmanı",
                            DurationMonths = 3,
                            FitnessTypeId = 2,
                            Name = "Pro Ağırlık",
                            Price = 800m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Kapsamlı yoga eğitimi",
                            DurationMonths = 1,
                            FitnessTypeId = 3,
                            Name = "Yoga Master",
                            Price = 600m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Esneklik ve güç için pilates",
                            DurationMonths = 2,
                            FitnessTypeId = 4,
                            Name = "Pilates Plus",
                            Price = 700m
                        });
                });

            modelBuilder.Entity("GymManagementSystem.Models.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<int>("FitnessTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FitnessTypeId");

                    b.ToTable("Trainers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ahmet@gym.com",
                            ExperienceYears = 5,
                            FitnessTypeId = 1,
                            FullName = "Ahmet Yılmaz",
                            Phone = "0532 111 2233",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 2,
                            Email = "mehmet@gym.com",
                            ExperienceYears = 8,
                            FitnessTypeId = 2,
                            FullName = "Mehmet Demir",
                            Phone = "0533 222 3344",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 3,
                            Email = "ayse@gym.com",
                            ExperienceYears = 6,
                            FitnessTypeId = 3,
                            FullName = "Ayşe Kaya",
                            Phone = "0534 333 4455",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 4,
                            Email = "fatma@gym.com",
                            ExperienceYears = 4,
                            FitnessTypeId = 4,
                            FullName = "Fatma Çelik",
                            Phone = "0535 444 5566",
                            Salary = 0m
                        });
                });

            modelBuilder.Entity("GymManagementSystem.Models.Member", b =>
                {
                    b.HasOne("GymManagementSystem.Models.Plan", "Plan")
                        .WithMany("Members")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymManagementSystem.Models.Trainer", "Trainer")
                        .WithMany("Members")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("GymManagementSystem.Models.Plan", b =>
                {
                    b.HasOne("GymManagementSystem.Models.FitnessType", "FitnessType")
                        .WithMany("Plans")
                        .HasForeignKey("FitnessTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FitnessType");
                });

            modelBuilder.Entity("GymManagementSystem.Models.Trainer", b =>
                {
                    b.HasOne("GymManagementSystem.Models.FitnessType", "FitnessType")
                        .WithMany("Trainers")
                        .HasForeignKey("FitnessTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FitnessType");
                });

            modelBuilder.Entity("GymManagementSystem.Models.FitnessType", b =>
                {
                    b.Navigation("Plans");

                    b.Navigation("Trainers");
                });

            modelBuilder.Entity("GymManagementSystem.Models.Plan", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("GymManagementSystem.Models.Trainer", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
